### PR TITLE
85 handle multiple rowspan columns during class parsing

### LINKED ISSUE #85: Check why `unit_d` is not reflecting in France
Mock html has defined 4 units for France

image

Parsed json only lists 3 for France

image

### PR DESCRIPTION
**Pull request by rnllv**
fixes #85

### CODE REVIEW

**Comment by rnllv** [comment]
image

**Comment by rnllv** [comment]
I've added few more test cases, and they are failing. Checking further.

**Comment by rnllv** [comment]
Issue fixed. Added another test. We can enhance our tests if mappings between existing  DataBrowser Unit fields and the corresponding published json fields are known.

**Comment by rnllv** [comment]
@IanMayo, can we extract and refactor this logic into a common class? It'll be helpful if other tables also have merged rows. 

Right now, we have duplicated code (almost) for remarks and classes.

**Comment by rnllv** [comment]
I went ahead and refactored it. The generated jsons are same (except for the random values) pre and post refactoring. Tests are also successful.

**Comment by rnllv** [comment]
Implementing few unit test cases for the merged row extraction logic, hence changing PR to draft.

**Comment by rnllv** [comment]
Unit tests added for class parsing. Marking this for review.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
