### PR TITLE
Extract flag and class tonal images

### LINKED ISSUE #48: Extracting Class images
Should the class images array be extracted from tonals page?

### PR DESCRIPTION
**Pull request by rnllv**
fixes #48

### CODE REVIEW

**Comment by rnllv** [comment]
I see only one image (flag image) for all non-Britain pages, except for Spain where it's the second.
For Britain (and similar pages), the first image is/should be the flag image.

@IanMayo, I'll implement the flag extraction based on the above, and put in required assert statements to validate our assumptions.

**Comment by IanMayo** [comment]
ok, some conflicts to be resolved (sometime), please @rnllv

**Comment by rnllv** [comment]
@IanMayo, conflict resolved. Please review.

**Comment by IanMayo** [comment]
@rnllv - we've added the `Flags` block towards the end of the JSON.  IMHO it would be neater to make `flag` an optional child within a `country`.  Plus, the `Flags` section looks like it is de-normalising other structures - which introduces some duplication/verbosity.

Is there a good reason for the `Flags` block?

**Comment by rnllv** [comment]
>IMHO it would be neater to make flag an optional child within a country

Yep, it should be. And there are few other changes in the class/unit properties required as mentioned in #100 

My plan was to make all those changes in one issue so that we can refer it again if required.

This issue was just to extract the images and place it (somewhere) in the json.

**Comment by IanMayo** [comment]
> My plan was to make all those changes in one issue so that we can refer it again if required.

Sure, ok

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
