### PR TITLE
100 improve country class data

### PR DESCRIPTION
**Pull request by IanMayo**
Use real data labels, improve units, provide wider set of examples of table layout

### CODE REVIEW

**Comment by rnllv** [comment]
@IanMayo, please confirm if we should be removing newline characters and trailing and leading spaces in remarks and harmonics.

image

**Comment by IanMayo** [comment]
yes, let´s trim leading/trailing spaces & newlines, please.

**Comment by rnllv** [comment]
Please review my changes.

**Review by rnllv — DISMISSED** [review]

**Comment by rnllv** [comment]
I've used the changes in Develop branch to override all conflicts (via `git merge -Xtheirs develop` )

The following is the summary of the below conflicts. Please review and approve.

Summary:
```
Range => MTBF
Max Speed => BHP
Av TPK => Av Temp
Power Related => Propulsion Related
Av Temp (previously TPK) value changed from kts to hrs
```

Conflicts:

```
diff --cc data/Britain/unit_da.html
index 7ed0fc7,d2ee488..0000000
--- a/data/Britain/unit_da.html
+++ b/data/Britain/unit_da.html
@@@ -21,17 -21,17 +21,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>14 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>12.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -53,15 -53,15 +67,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>12.8:1</td>
 +          <td>22 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -74,7 -74,7 +98,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/France_Composites/unit_a.html
index cdf259e,b61765d..0000000
--- a/data/France_Composites/unit_a.html
+++ b/data/France_Composites/unit_a.html
@@@ -21,24 -21,24 +21,44 @@@
          </tr>
          <tr>
            <td><strong>Cruise Plant</strong></td>
++<<<<<<< HEAD
 +          <td>2 * V8 Diesel</td>
 +          <td><strong>Shaft x Blade</strong></td>
 +          <td>3 x 3</td>
++=======
+           <td>4 * PR32 Diesel Engines</td>
+           <td><strong>Shaft x Blade</strong></td>
+           <td>2 * 4 (GRR)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>16 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>41.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -60,15 -60,15 +80,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>41.8:1</td>
 +          <td>16 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -81,7 -81,7 +111,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td colspan="6">Auxiliary Sources</td>
diff --cc data/France_Legacy/unit_d_star.html
index 61be09b,cde367e..0000000
--- a/data/France_Legacy/unit_d_star.html
+++ b/data/France_Legacy/unit_d_star.html
@@@ -21,17 -21,17 +21,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>21 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>42.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -54,15 -54,15 +68,24 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
            <td>412.8:1</td>
++<<<<<<< HEAD
 +          <td>21 kts</td>
++=======
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -77,7 -77,7 +100,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Iceland/britain_1.html
index 28b21f3,8b28174..0000000
--- a/data/Iceland/britain_1.html
+++ b/data/Iceland/britain_1.html
@@@ -21,17 -21,17 +21,30 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">4 DEW Alpha Batteries</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>N/A</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>N/A</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
++>>>>>>> develop
            <td>400</td>
          </tr>
          <tr>
            <td><strong>Reduction Ratio</strong></td>
++<<<<<<< HEAD
 +          <td>12.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -53,14 -53,14 +66,23 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>12.8:1</td>
++=======
+           <td>412.8:1</td>
++>>>>>>> develop
            <td>400</td>
            <td>~14</td>
          </tr>
@@@ -74,7 -74,7 +96,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Iceland/unit_da.html
index 9d55795,d2ee488..0000000
--- a/data/Iceland/unit_da.html
+++ b/data/Iceland/unit_da.html
@@@ -21,17 -21,17 +21,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>23 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>41.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -53,15 -53,15 +67,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>41.8:1</td>
 +          <td>23 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -74,7 -74,7 +98,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Iceland_Composite/unit_ab.html
index 06b7c7a,90563e6..0000000
--- a/data/Iceland_Composite/unit_ab.html
+++ b/data/Iceland_Composite/unit_ab.html
@@@ -21,17 -21,17 +21,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>26 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>32.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -53,15 -53,15 +67,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>32.8:1</td>
 +          <td>26 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -74,7 -74,7 +98,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Spain1/unit_db.html
index fbf57a6,14c4146..0000000
--- a/data/Spain1/unit_db.html
+++ b/data/Spain1/unit_db.html
@@@ -38,17 -38,17 +38,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>11 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>2.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -70,15 -70,15 +84,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>2.8:1</td>
 +          <td>11 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -91,7 -91,7 +115,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Wales/unit_da.html
index 93124fd,d2ee488..0000000
--- a/data/Wales/unit_da.html
+++ b/data/Wales/unit_da.html
@@@ -21,17 -21,17 +21,31 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">None</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>400 nm at 6 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
 +          <td>9 kts</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Reduction Ratio</strong></td>
 +          <td>1.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>14hrs & 12 ltr/hr</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
+           <td>400 hrs</td>
+         </tr>
+         <tr>
+           <td><strong>Reduction Ratio</strong></td>
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -53,15 -53,15 +67,25 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK (Guide)</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp (Guide)</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>1.8:1</td>
 +          <td>9 kts</td>
++=======
+           <td>412.8:1</td>
+           <td>400 hrs</td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -74,7 -74,7 +98,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
diff --cc data/Wales_Standalones/Wales_1a.html
index 28c3ea5,a9d1aef..0000000
--- a/data/Wales_Standalones/Wales_1a.html
+++ b/data/Wales_Standalones/Wales_1a.html
@@@ -21,17 -21,17 +21,30 @@@
          <tr>
            <td rowspan="2"><strong>Boost Plant</strong></td>
            <td rowspan="2">4 DEW Alpha Batteries</td>
++<<<<<<< HEAD
 +          <td><strong>Range</strong></td>
 +          <td>N/A</td>
 +        </tr>
 +        <tr>
 +          <td><strong>Max Speed</strong></td>
++=======
+           <td><strong>MTBF</strong></td>
+           <td>N/A</td>
+         </tr>
+         <tr>
+           <td><strong>BHP</strong></td>
++>>>>>>> develop
            <td>400</td>
          </tr>
          <tr>
            <td><strong>Reduction Ratio</strong></td>
++<<<<<<< HEAD
 +          <td>9.8:1</td>
 +          <td><strong>Av TPK</strong></td>
++=======
+           <td>412.8:1</td>
+           <td><strong>Av Temp</strong></td>
++>>>>>>> develop
            <td>~14</td>
          </tr>
          <tr>
@@@ -88,14 -88,14 +101,23 @@@
            <td>Mode</td>
            <td>Shaft x Blade</td>
            <td>R:R</td>
++<<<<<<< HEAD
 +          <td>Max Speed</td>
 +          <td>Av TPK</td>
++=======
+           <td>BHP</td>
+           <td>Av Temp</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>4 Diesel</td>
            <td>PTR</td>
            <td>2 * 4 (GRR)</td>
++<<<<<<< HEAD
 +          <td>9.8:1</td>
++=======
+           <td>412.8:1</td>
++>>>>>>> develop
            <td>400</td>
            <td>~14</td>
          </tr>
@@@ -109,7 -109,7 +131,11 @@@
            <td colspan="2">Remarks</td>
          </tr>
          <tr>
++<<<<<<< HEAD
 +          <td colspan="6">Power Related</td>
++=======
+           <td colspan="6">Propulsion Related</td>
++>>>>>>> develop
          </tr>
          <tr>
            <td>SR</td>
```

**Review by rnllv — DISMISSED** [review]

**Comment by IanMayo** [comment]
Yes, those changes look valid @rnllv 

Are you able to resolve the conflict in the test file please?

**Review by rnllv — APPROVED** [review]

**Comment by rnllv** [comment]
The merge has resolved the unit test errors. Please check and approve.

**Pull request merged**
