### PR TITLE
Set cwd drive to target destination if applicable

### LINKED ISSUE #153: Target directory should always be in current working directory

### PR DESCRIPTION
**Pull request by rnllv**

### CODE REVIEW

**Comment by IanMayo** [comment]
Is there a reason why we don't _always_ set the full path?
```
os.path.splitdrive(os.getcwd())[0] + "//" + "target/"
```

**Comment by IanMayo** [comment]
oops :-)

**Comment by rnllv** [comment]
>Is there a reason why we don't always set the full path?

Yep. I won't be able to test it on Linux. :wink:

**Comment by IanMayo** [comment]
> > Is there a reason why we don't always set the full path?
> 
> Yep. I won't be able to test it on Linux. 😉

Hmm, regardless of the ´drive letter´ issue, on Win/Mac/Linux we can set TARGET_DIRECTORY to the absolute path for the current working folder.

**Comment by rnllv** [comment]
>Hmm, regardless of the ´drive letter´ issue, on Win/Mac/Linux we can set TARGET_DIRECTORY to the absolute path for the current working folder.

Done.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
