### PR TITLE
Add index.ditamap to target dir

### LINKED ISSUE #262: Copy ditamap to destination
In the `data` folder is an `index.ditamap` this is the `root` of the new document.

1. force delete any folder called `target` in the current folder
2. create a folder called `target` in the current folder
3. copy `index.ditamap` and `welcome.dita`  from `data` to `target/dita`
4. run the [command](https://github.com/DeepBlueCLtd/LegacyMan/issues/260) to export the ditamap to html.  Note: you'll have to download DITA-OT, and declare it's root folder as a DITA_OT environment variable  on your machine (note the switch from hyphen to underscore, hyphens don't work in env variables on mac/linux). I'm using version 3.7.4.
5. you will also need to have Java installed on your machine.
6. Insert a line in the console logging to report `Publish complete after xxx seconds. Root file at xxx\xxx\xxx`.  This will come after `parse complete` entry.

Note: for the output of this task, I'm expecting:
* an updated `parser.parser
* the `index,ditamap` and `welcome.dita`  in `data`
* a `target` folder that just contains the copied `index.ditamap` in the `target/dita` folder
* the published content in `target/html`.  No, it's not great to put generated content into version control, but it's a quick way for me to review/verify what has changed from the previous publish.

### PR DESCRIPTION
**Pull request by ebenezer-melkamu**
Fixes #262 

### Modification
* Added `index.ditamap` to `target/dita`

### CODE REVIEW

**Comment by ebenezer-melkamu** [comment]
@IanMayo I made a mistake, i should have pulled the latest code from origin to `develop` and i should have created my feature branch from there, i got merge conflicts here

**Comment by ebenezer-melkamu** [comment]
@IanMayo should i delete this feature-branch and submit another PR?

**Comment by IanMayo** [comment]
Yes, it will be easier to create a new branch :-)

But note: this issue isn't about manually copying the file over.  It's about modifying `parser.parser` to copy the file over.

**Comment by ebenezer-melkamu** [comment]
@IanMayo ok got it, i will push another PR

**Pull request closed without merging**
