### PR TITLE
175 images not shown in databrowser

### LINKED ISSUE #175: Images not shown in DataBrowser
Images aren't being shown, though I see they are in `class_images` collection.

The URL is an absolute path to the `target` folder in `LegacyMan`. For this specific field, we need to switch to relative paths.  I _guess_ we can just replace the `target_URL` part of the path with `./`.

### PR DESCRIPTION
**Pull request by rnllv**
fixes #175

### CODE REVIEW

**Comment by rnllv** [comment]
Tested in DataBrowser after copying the images from target directory in LegacyMan and editing absolute paths to match the relative paths with respect to build directory of DataBrowser.

image

**Comment by rnllv** [comment]
Please review.

**Comment by rnllv** [comment]
@IanMayo, I've resolved the merge conflict. Please review.

**Review by IanMayo — APPROVED** [review]
Look forward to testing on real data :-)

**Pull request merged**
